#!/bin/bash

source /www/cgi-bin/setup.inc
source /www/cgi-bin/url.inc
source /www/cgi-bin/utils.inc
source /www/cgi-bin/leds.inc
source /www/cgi-bin/ears.inc
source /www/cgi-bin/webcam.inc

KillProcess LEDS

ReadUrlParam
TDIR=$CNF_DATADIR"/Snapshots/"

SILENT=${URLParam[silent]}
            
FN="snapshot"_`date +'%Y_%m_%d_%H_%M_%S'`
TakeSnapshot

if [ ! -e "$CNF_DATADIR/Run/karotz.sleep" ]; then
  LedsRestore
  if [ "$SILENT" == "" ]; then
    PlaySound /usr/karotz/res/sounds/webcam.mp3
  fi
fi

if [ ! -e "/tmp/picture.jpg" ]; then
    exit 0
fi

printf "Server: OpenKarotz WebServer 1.0\r\n"
printf "Connection: close\r\n"
printf "Accept-Ranges: bytes\r\n"
printf "Content-type: image/jpeg\r\n"
printf "Access-Control-Allow-Origin: *\r\n"
printf "\r\n"
cat /tmp/picture.jpg

